Update dockerfile, add echo to stderr for rubocop
- Update Dockerfile
  - Change default CMD instruction to ["tox"]
  - Delete xterm env variable
- Update rubocop
  - Add echo to stderr >&2
- Update circleci config.yml
  - Update image to tag 0.0.2

diff --git a/bin/rubocop b/bin/rubocop
--- a/bin/rubocop
+++ b/bin/rubocop
@@ -2,7 +2,7 @@
 set -euo pipefail
 
 if ! command -v 'bundle' >/dev/null; then
-  echo "Executable \`bundle\` not found"
+  echo "Executable \`bundle\` not found" >&2
   exit 1
 fi
 
